### PR TITLE
Fixed Hangman Draw

### PR DESCRIPTION
**Pull request by RogueMaster**
See changes. 

Do you think you could make one that will work with an English keyboard? 

Also, would you have instructions on how to create the BIN file? 

I have included your application in my firmware, it is great!

### CODE REVIEW

**Comment by bolknote** [comment]
Hi! Thank you for your feedback, I am very pleased!

Could you tell me please which bug is being fixed by your PR so that I understand what exactly is not working?

Regarding the English language, I had plans to make a two-item language selection menu when starting the game. Would it be convenient, do you think?

**Comment by bolknote** [comment]
I forgot to tell you about creating BIN files. I don't have compatibility with ufbt yet (I'm going to do it this week), so creation is only possible by fbt:

`./fbt fap_hangman`

**Comment by RogueMaster** [comment]
How does ./fbt fap_hangman create the .bin? What file needs to be provided first, csv?

This PR is meant to fix a bug drawing the hangman with inverted colors. Prior to these changes, the game would show a white box when the firmware is set to invert colors. I have also re-worked the image assets to be black and white in case that helps rendering, let me know if I should include those changes in this PR.

**Comment by bolknote** [comment]
Thank you for your fix!

I added a commit that allows you to create BIN by ufbt too: 1f4b41101c6aff1267e7fa92f402d060846a5944

**Comment by RogueMaster** [comment]
I'm sorry, could you describe further how to create the BIN file from a dictionary file? I guess it isn't really necessary since we don't have English support yet, would just be nice to know.

**Comment by bolknote** [comment]
I'm sorry, I didn't understand what it was about at first.

Currently the dictionary files contains Russian words separated by a line feed. It is transformed into BIN by the following command:

`LANG=C LC_ALL=C sed 's/\xD0//g' dict.bin`

**Comment by RogueMaster** [comment]
> LANG=C LC_ALL=C sed 's/\xD0//g' dict.bin

You don't seem to be specifying any source file with this command, like dict.csv?

**Comment by bolknote** [comment]
Somehow I didn't think about it. I will attach it together with English support.

I just don't know where to get a dictionary for English.

**Comment by RogueMaster** [comment]
[dict.csv](https://github.com/bolknote/Flipper-Zero-Hangman-Game/files/13212262/dict.csv)
I made this one with anime titles 😄

**Comment by bolknote** [comment]
OMG :-)

**Pull request merged**
